import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/components/organisms/footer/Footer';
import Header from '@/components/organisms/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
